	.text
	.file	"mas_bkops_sysfs.c"
	.globl	mas_bkops_add_debugfs   // -- Begin function mas_bkops_add_debugfs
	.p2align	2
	.type	mas_bkops_add_debugfs,@function
mas_bkops_add_debugfs:                  // @mas_bkops_add_debugfs
.Lmas_bkops_add_debugfs$local:
// %bb.0:
	mov	w0, wzr
	ret
.Lfunc_end0:
	.size	mas_bkops_add_debugfs, .Lfunc_end0-mas_bkops_add_debugfs
                                        // -- End function
	.ident	"Android (6443078 based on r383902) clang version 11.0.1 (https://android.googlesource.com/toolchain/llvm-project b397f81060ce6d701042b782172ed13bee898b79)"
	.section	".note.GNU-stack","",@progbits
